# Generated by Django 5.1.4 on 2025-01-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
