# Generated by Django 5.1.4 on 2025-02-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
