# Generated by Django 5.1.4 on 2025-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_user_user_image_user_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT'),
        ),
    ]
