# Generated by Django 5.1.4 on 2025-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='win_games',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
