# Generated by Django 5.1.6 on 2025-03-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_friend_user_friends_invitation_user_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_otp',
            field=models.CharField(default=False, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tow_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='auth_app.friend'),
        ),
    ]
